### ISSUE TITLE
benchmark_da-tacos URL is not working

### ISSUE THREAD

**Issue by mayassin** [furkanyesiler/move#5]
On running the benchmark_da-tacos, I am met with the following error `Permission denied: https://drive.google.com/uc?id=1y5g1whcd7bG6CiU0_cSqmpNR33hdKrby 
Maybe you need to change permission over 'Anyone with the link'? `

I believe the google drive link is either broken or permissions should be updated.

**Comment by cc-cherie** [comment]
Hi, have you get the link of the benchmark_da-tacos URL ?
